workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18.19.0
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "com.talkcaddy.app"
        APP_NAME: "Talk-Caddy"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: Build web app
        script: |
          pnpm build
      - name: Update Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "App" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18.19.0
      java: 17
      android_signing:
        - talkcaddy_keystore
      groups:
        - android_credentials
      vars:
        PACKAGE_NAME: "com.talkcaddy.app"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install -g pnpm
          pnpm install
      - name: Build web app
        script: |
          pnpm build
      - name: Update Capacitor
        script: |
          npx cap sync android
      - name: Build Android AAB
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
